## IMAGEM INICIAL - base-go

# Imagem Base
FROM golang:1.20 as base-go

# Define o diretorio de trabalho
WORKDIR /usr/src/app

## Copia os arquivos da pasta do dockerhost para o container
COPY go/go.mod go/pgm.go ./  

## Compila o programa
RUN go build -v -o /usr/local/bin/app ./...

## CMD ["app"]

## -----------
## IMAGEM FINAL
## ------------
# Imagem Base - scratch
FROM scratch

# Copia os dados do Estagio Incial para a Imagem Final
COPY --from=base-go /usr/local/bin/app .
CMD [ "./app" ]